baseURL = "https://xiaochendev.github.io/"
title = "x'Notes"
theme = "PaperMod"

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = false
  ShowCodeCopyButtons = true
  ShowToc = false
  ShowShareButtons = false
  ShowHomeContent = false  
  mainSections = ["posts"]
  disableThemeToggle = false
  disableSchema = true
  ShowFullTextinRSS = false 
  disableSeo = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1

[params.socialIcons]
  github = "https://github.com/xiaochendev"
