baseURL = "https://xiaochendev.github.io/"
title = "x'Notes"
theme = "PaperMod"

[params]
  defaultTheme = "auto"

  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = false
  ShowToc = false
  ShowShareButtons = false
  
  mainSections = ["posts"]
 
  ShowHomeContent = false  
  ShowCodeCopyButtons = true
  ShowRssButtonInSectionTermList = false

  ShowSocialIcons = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1

[params.socialIcons]
  github = "https://github.com/xiaochendev"
