baseURL = "https://xiaochendev.github.io/"
title = "My Blog"
theme = "PaperMod"

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = false
  ShowCodeCopyButtons = true
  ShowToc = false
  ShowShareButtons = false
  ShowHomeContent = false  

  homeInfoParams = { Title = "Xiao' Notes", Content = "Machine learning & systems notes" }

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1
